fix #25
rocktimsaikia/cambd-cli pull request #26
Opened 2022-11-26 10:15 UTC by xerenahmed

fix #25

Before
```

consider (verb)
To spend time thinking about a possibility or making a decision.

Examples:
• Don't make any decisions before you've considered the situation.
• [ + question word ] Have you considered what you'll do if you don't get the job?

=====*=====

consider (verb)
To think about a particular subject or thing or about doing something or about whether to do something.

Examples:
• Consider Clara Barton, who founded the American Red Cross.
• We considered moving to California, but decided not to.

```

After:
```

consider (verb) B1 [ I or T ]
To spend time thinking about a possibility or making a decision.

Examples:
• Don't make any decisions before you've considered the situation.
• [ + question word ] Have you considered what you'll do if you don't get the job?

=====*=====

consider (verb) C1 [ T ]
To give attention to a particular subject or fact when judging something else.

Examples:
• You've got to consider the time element when planning the whole project.
• [ + question word ] If you consider how long he's been learning the piano, he's not very good.

=====*=====

consider (verb) C2 [ T ]
To care about or respect other people or their feelings and wishes.

Examples:
• Did you consider your mother and how she's going to feel about you leaving?
• She never considers anyone but herself - she's totally selfish!

=====*=====

consider (verb) B2 [ T often + obj + (to be) + noun/adj ]
To believe someone or something to be, or think of him, her, or it as something.

Examples:
• He is currently considered (to be) the best British athlete.
• We don't consider her to be right for the job.

=====*=====

consider (verb)
To think about a particular subject or thing or about doing something or about whether to do something.

Examples:
• Consider Clara Barton, who founded the American Red Cross.
• We considered moving to California, but decided not to.

=====*=====

consider (verb)
To care about or respect.

Examples:
• Before raising the admission prices, consider the fans.

=====*=====

consider (verb)
To believe to be; to think of as.

Examples:
• What some people would consider a personal attack, Andy considers a friendly discussion.

```

Warning: an error occurs if cache is from old code. Because cache do not have "Info" data.
```
print(f"\n[bold green]{word}[/] [dim]({definition['Type']}) {definition['Info']}[/]")
KeyError: 'Info'
```

2022-11-26 14:37 UTC, rocktimsaikia commented
Personally I only need the UK definitions. But I guess there can be a option to show the US definitions too ie, `--dictionary` and it should default to `UK`.

I don't want the output to be verbose and hard to read. We can add the which dictionary it is sourcing from ie, UK/US; but get rid of the other infos like `B2 [ T often + obj + (to be) + noun/adj ]`. The definition, word type and dictionary source is enough info already.

This should be the final outout for the header:
```sh
consider (verb) US
```

2022-11-26 15:32 UTC, xerenahmed commented
Well, the other info can be useful but it would be hidden if an option is not used like `--describe`

2022-11-26 18:05 UTC, rocktimsaikia requested changes

2022-11-26 18:05 UTC, rocktimsaikia commented on cambd/cambd.py
> -            return get_definitions(original_word)
Why remove this? This is required to handle past and particle word lookup.

2022-11-26 18:05 UTC, rocktimsaikia commented on cambd/cambd.py
> +            def_info = def_info.get_text() if def_info is not None else None
I have never used this info tbh. It just makes it more verbose. Lets remove this for now.

2022-11-26 18:08 UTC, xerenahmed commented on cambd/cambd.py
> -            return get_definitions(original_word)
In my reproduces I didn't see .dx-h element. And it made some errors when word_type is None. Can you send me a valid word for that? So I can handle.

2022-11-26 18:10 UTC, xerenahmed commented on cambd/cambd.py
> +            def_info = def_info.get_text() if def_info is not None else None
I don't use [ T + I noun] someting but B2 C1 infos tells me how it is common or rare in usage. I found this useful when learning english though.

2022-11-26 18:12 UTC, rocktimsaikia commented on cambd/cambd.py
> -            return get_definitions(original_word)
Try `nuked` with the current live version of cambd. And try it without this peace of code, You will see the diff

2022-11-26 18:39 UTC, xerenahmed commented on cambd/cambd.py
> -            return get_definitions(original_word)
```
nuked (None) UK
Past simple and past participle of nuke.

Examples:

=====*=====

nuked (None) UK   informal
To bomb somewhere with nuclear weapons.

Examples:
• The two countries were threatening to nuke each other.
```

This is more significant to understand actually. If you want the "nuked" definition you want to learn that it's past tense of nuke, you didn't want to see nuked means "bomb somewhere"

2022-11-26 19:41 UTC, xerenahmed commented on cambd/cambd.py
> +            def_info = def_info.get_text() if def_info is not None else None
Made `-v` `--verbose`flag for this.

2022-11-27 07:58 UTC, rocktimsaikia commented
With the addition of the new field in the table. It does not store all the definitions. It will only store one definition by default.

![image](https://user-images.githubusercontent.com/33410545/204124970-2fd785a2-181d-4a0a-aca4-4baf3d3a5d4a.png)

It should store all definitions by default including both uk,us so that looking up the same word does not scrap the whole page again. Caching of all definitions should NOT depend on what options are being passed.

2022-11-27 09:33 UTC, rocktimsaikia approved these changes

2022-11-27 09:33 UTC, rocktimsaikia commented
Thanks for contributing. Looks good.

2022-11-27 09:34 UTC, merged